# Generated by Django 3.2.8 on 2021-11-17 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ruby', '0003_auto_20211117_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Ruby.product'),
        ),
    ]
